Add transcription line tool explanation
zooniverse/Panoptes-Front-End pull request #5905
Opened 2021-02-25 21:21 UTC by srallen

Staging branch URL: https://pr-{NUMBER}.pfe-preview.zooniverse.org

This add explanatory text a bout the transcription line:

<img width="510" alt="Screen Shot 2021-02-25 at 3 19 15 PM" src="https://user-images.githubusercontent.com/5016731/109219257-fc735900-777c-11eb-88fd-ed5f58af5524.png">

Previewed at: https://local.zooniverse.org:3735/lab/1764/workflows/3392

@snblickhan and @beckyrother is this text ok for the editor?

# Required Manual Testing

- [ ] Does the non-logged in home page render correctly?
- [ ] Does the logged in home page render correctly?
- [ ] Does the projects page render correctly?
- [ ] Can you load project home pages?
- [ ] Can you load the classification page?
- [ ] Can you submit a classification?
- [ ] Does talk load correctly?
- [ ] Can you post a talk comment?

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on Travis?

# Optional

- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

2021-02-25 22:02 UTC, beckyrother requested changes
Just to help readability, please change the 'This is a 2-click line mark tool which has pre-set colors. These colors map to the following states:' text to 13px Karla (the smaller type size shown here:)

![image](https://user-images.githubusercontent.com/1392130/109225323-bae5ac80-7782-11eb-8183-4d663c53f33d.png)

The text itself looks good though!

2021-02-26 17:01 UTC, srallen commented
@beckyrother I've updated the styles and also applied the color and font size elsewhere where it made sense. It looked a  little odd to have it applied to the definition list but not the other new 'headers'. Check it out: https://pr-5905.pfe-preview.zooniverse.org/lab/1764/workflows/3392

2021-02-26 17:01 UTC, snblickhan commented
The only surprise to me was that the previous marks are Purple and not Pink -- I've referred to them as "Pink" throughout the explanatory task in the beta project.

Otherwise the text looks accurate and I'm supportive of it moving forward!

2021-02-26 17:06 UTC, srallen commented
@snblickhan This is why I check! It's definitely not a true purple, but I labeled it as purple because we have a warm (hot?) pink color in the mix: https://github.com/zooniverse/front-end-monorepo/tree/master/packages/lib-grommet-theme. Scroll through the readme to find the `drawing-purple` and `drawing-pink` colors. Any other names for these are welcome because naming is hard 😆

2021-02-26 17:07 UTC, snblickhan commented
oh no @beckyrother help

2021-02-26 17:13 UTC, srallen commented
I spent a bit of time trying to figure out color variants for the highlighter series... Googleing the hex value sometimes helps. This site says #FF40FF Pink Flamingo https://www.htmlcsscolor.com/hex/FF40FF and #FF2B70 is Radical Red https://www.htmlcsscolor.com/hex/FF2B70

.... These names might not be helpful though. AHHHH 😆

2021-02-26 18:43 UTC, beckyrother commented
It's right on the border between purple and pink! I think either is appropriate as long as we're consistent – there isn't another color on the list that could be construed as either of those, so even just by using the process of elimination people will understand which one we're talking about it. Sounds like if all the help text use "pink" let's go with that here as well.

2021-02-26 22:05 UTC, srallen commented
@beckyrother ok, what should we call #FF2B70? I'm inclined to rename the variable names in the code so we don't confuse ourselves in the future.

2021-02-26 23:03 UTC, beckyrother commented
Should we just call it Pink for simplicity? Also a fan of "Pink Flamingo" if we're feeling spicy

2021-02-26 23:04 UTC, snblickhan commented
I am 100% team Pink Flamingo, fwiw

2021-03-01 15:01 UTC, srallen commented
@beckyrother sorry, I'm not being clear. The color I'm asking about is not the pink-like color that I had labeled as purple. We can rename that to be pink. I'm asking about this color in the theme, not used by transcription tools, but available to the standard drawing tools, also pink-like: https://www.htmlcsscolor.com/hex/FF2B70 What should we label this one?

2021-03-01 17:34 UTC, beckyrother commented
Ohh I understand. Sorry for the confusion! What about 'Ruby' ?

2021-03-02 15:10 UTC, shaunanoordin approved these changes
## PR Review

😆 While everyone argues over the colours, I wanted to pop in and give this PR a 👍 from a code perspective. Basic text content update, LGTM.

But just to make sure I don't miss a chance to stir up trouble: _how about [magenta-ish amaranthine fuchsia](https://en.wikipedia.org/wiki/Shades_of_magenta)?_

2021-03-02 15:46 UTC, srallen commented
@beckyrother I've updated the name. Is the editor now ok for approval? Thanks!

2021-03-02 16:07 UTC, beckyrother approved these changes
Works for me! 🎉

2021-03-04 15:24 UTC, merged