POC of bifurcation of SimpleDropdown for FEMLab in PFE
zooniverse/Panoptes-Front-End pull request #6820
Opened 2023-09-11 19:32 UTC by kieftrav

# Overview
Bifurcates the Dropdown in PFE & FEMLab interface to implement SimpleDropdown only in FEMLab.

# Required Manual Testing
- PFE without FEMLab enabled for a Dropdown:
  [] - Should still display the "+ Add a Dropdown" interface
  [] - Should still have the "Allow Create" toggle in the Edit Modal
- PFE with FEMLab enabled for a Dropdown should:
  [] - Should not display the "+ Add a Dropdown" interface
  [] - Should not have the "Allow Create" toggle in the Edit Modal

# Review Checklist
- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Does it work on mobile?
- [ ] Can you `npm ci` and app works as expected?
- [ ] If the component is in coffeescript, is it converted to ES6? Is it free of eslint errors? Is the conversion its own commit?
- [ ] Are the tests passing locally and on GitHub Actions?

# Optional
- [ ] Have you replaced any `ChangeListener` or `PromiseRenderer` components with code that updates component state?
- [ ] If changes are made to the classifier, does the dev classifier still work?
- [ ] Have you [resized and compressed](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/image-optimization) any image you've added?
- [ ] Have you added in [flow type annotations](https://flowtype.org/docs/type-annotations.html)?
- [ ] Have you followed the [Springer guidelines for commit messages](https://github.com/springernature/frontend-playbook/blob/master/git/git.md#commit-messages)?

2023-09-11 19:37 UTC, kieftrav commented
Example of PFE without FEMLab Enabled:

https://github.com/zooniverse/Panoptes-Front-End/assets/733986/299eb4b7-f89c-40e4-9402-596847342659

2023-09-11 19:38 UTC, kieftrav commented
Example of PFE with FEMLab Enabled for SimpleDropdown:

https://github.com/zooniverse/Panoptes-Front-End/assets/733986/d3c54989-239e-4b41-9399-539237b49cd4

2023-09-14 19:09 UTC, shaunanoordin requested changes
## PR Review

Affects: Project Builder -> Workflow Editor (PFE Lab & FEM Lab) -> Dropdown Tasks

This PR modifies the Dropdown Task in the Workflow Editor, making it so some dropdown task options are no longer available on FEM Lab mode. This is the first step in making a distinct & new version of dropdown tasks available on **FEM Lab,** while _maintaining_ the original version of dropdown tasks on **PFE Lab.**

- On PFE Lab (viewable by appending ?pfeLab=true to the URL), the controls marked in red in the screenshots below ARE visible and can be interacted with.
- On FEM Lab (?femLab=true), the controls marked in red AREN'T visible.

<img width="533" alt="image" src="https://github.com/zooniverse/Panoptes-Front-End/assets/13952701/797e4523-0fbc-4ccf-9353-a009d552658a">

<img width="181" alt="image" src="https://github.com/zooniverse/Panoptes-Front-End/assets/13952701/f0cd588c-f581-4cd7-a01f-26900876340f">

### Testing

Tested with macOS + Chrome

Testing URLs:
- FEM Lab: https://local.zooniverse.org:3735/lab/1966/workflows/3773?femLab=true
- PFE Lab: https://local.zooniverse.org:3735/lab/1966/workflows/3773?pfeLab=true

Project 1966 has the 'dropdown' experimental tool enabled. Workflow 3773 has 1 task, which is a Dropdown Task with 5 options.

⚠️ tests will fail if Project 1966 has the 'shortcut' experimental tool enabled, due to the pfeLab variable not being passed properly in `task-editor.jsx`. This is a separate bug for a separate PR, though.

Testing steps:
- Load the workflow. Observe the Dropdown Task.
  - PFE Lab version should show all controls (marked red in the screenshots above); FEM Lab version shouldn't show those controls.
- Modify the Dropdown Task.
  - Change the question, change the dropdown's title, add & delete dropdown options.
 
❗ ISSUE DETECTED

Problem: on FEM Lab, if we attempt to change the dropdown's title OR check/uncheck the 'Required' box, an error will be thrown.

https://github.com/zooniverse/Panoptes-Front-End/assets/13952701/db01bff3-8346-4bb1-b63b-56ab4cf6c231

Analysis: this error occurs because in FEM Lab, the 'allowCreate' checkbox doesn't exist. However, the `editSelect()` function (triggered by title's/required's/allowCreate's onChange handler) still looks for `@refs.allowCreate.checked`.

Solution: check for `@refs.allowCreate` before using `@refs.allowCreate.checked`

### Status

This PR requires 3x changes before it's good to merge.

Requested changes are all for `app/classifier/tasks/dropdown/dropdown-dialog.cjsx`

Code cleanup:
- [x] remove `isFemLab: false` in getDefaultProps() OR replace it with `pfeLab: false`
- [x] remove stray `{props.isFemLab}`

Reason: isFemLab is no longer used.

Code fixes:
- [ ] in `editSelect()` (the function, not the confusingly similarly named state), change `select.allowCreate = @refs.allowCreate.checked` to `select.allowCreate = if @refs.allowCreate then @refs.allowCreate.checked else false`

Or, in full:
```
  editSelect: ->
    select = @state.editSelect
    select.title = @refs.title.value
    select.required = @refs.required.checked
    select.allowCreate = if @refs.allowCreate then @refs.allowCreate.checked else false
    @setState editSelect: select
```

Reason: fixes the issue noted above. When in FEM Lab mode, the allowCreate value must always be false.

Other than these 3 CRs, the code changes look good, functionality checks out, and the updated test properly checks for the PFE & FEM differences. Sweet. 👌

2023-09-14 22:25 UTC, goplayoutside3 commented
Just a quick note I'm editing the description to link Issue https://github.com/zooniverse/Panoptes-Front-End/issues/6765 to this PR.

2023-09-20 11:15 UTC, shaunanoordin approved these changes
## PR Review (Update)

Awesome, thank you for making those changes! This PR is now LGTM 👍

2023-09-20 16:21 UTC, merged